export const STORAGE_KEY = {
    IS_DISPLAY_FURIGANA : "IS_DISPLAY_FURIGANA",
    IS_DISPLAY_TRANSLATED_CONTENT : "IS_DISPLAY_TRANSLATED_CONTENT",
    IS_LIKE_CONTENT : "IS_LIKE_CONTENT",
    NEWS_LOCAL: "NEWS_LOCAL",
    SETUP_FIRST_TIME: "SETUP_FIRST_TIME",
    LastModified: "LastModified"
}